# Generated by Django 3.0.8 on 2020-08-10 15:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'predsjednik povjerenstva za diplomske ispite - strojarstvo'), (2, 'zamjenik povjerenstva za diplomske ispite - strojarstvo'), (3, 'djelovođa povjerenstva za diplomske ispite - strojarstvo'), (4, 'predsjednik povjerenstva za diplomske ispite - brodogradnja'), (5, 'zamjenik povjerenstva za diplomske ispite - brodogradnja'), (6, 'djelovođa povjerenstva za diplomske ispite - brodogradnja'), (7, 'predsjednik povjerenstva za diplomske ispite - elektrotehnika'), (8, 'zamjenik povjerenstva za diplomske ispite - elektrotehnika'), (9, 'djelovođa povjerenstva za diplomske ispite - elektrotehnika'), (10, 'predsjednik povjerenstva za diplomske ispite - računarstvo'), (11, 'zamjenik povjerenstva za diplomske ispite - računarstvo'), (12, 'djelovođa povjerenstva za diplomske ispite - računarstvo'), (13, 'predsjednik povjerenstva za završne ispite - strojarstvo sveučilišni'), (14, 'zamjenik povjerenstva za završne ispite - strojarstvo sveučilišni'), (15, 'djelovođa povjerenstva za završne ispite - strojarstvo sveučilišni'), (16, 'predsjednik povjerenstva za završne ispite - brodogradnja sveučilišni'), (17, 'zamjenik povjerenstva za završne ispite - brodogradnja sveučilišni'), (18, 'djelovođa povjerenstva za završne ispite - brodogradnja sveučilišni'), (19, 'predsjednik povjerenstva za završne ispite - elektrotehnika sveučilišni'), (20, 'zamjenik povjerenstva za završne ispite - elektrotehnika sveučilišni'), (21, 'djelovođa povjerenstva za završne ispite - elektrotehnika sveučilišni'), (22, 'predsjednik povjerenstva za završne ispite - računarstvo sveučilišni'), (23, 'zamjenik povjerenstva za završne ispite - računarstvo sveučilišni'), (24, 'djelovođa povjerenstva za završne ispite - računarstvo sveučilišni'), (25, 'predsjednik povjerenstva za završne ispite - strojarstvo stručni'), (26, 'zamjenik povjerenstva za završne ispite - strojarstvo stručni'), (27, 'djelovođa povjerenstva za završne ispite - strojarstvo stručni'), (28, 'predsjednik povjerenstva za završne ispite - brodogradnja stručni'), (29, 'zamjenik povjerenstva za završne ispite - brodogradnja stručni'), (30, 'djelovođa povjerenstva za završne ispite - brodogradnja stručni'), (31, 'predsjednik povjerenstva za završne ispite - elektrotehnika stručni'), (32, 'zamjenik povjerenstva za završne ispite - elektrotehnika stručni'), (33, 'djelovođa povjerenstva za završne ispite - elektrotehnika stručni'), (34, 'mentor'), (35, 'komentor'), (36, 'član povjerenstva za obranu')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_study', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('jmbag', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Diplomski sveučilišni studij strojarstvo'), (2, 'Diplomski sveučilišni studij brodogradnja'), (3, 'Diplomski sveučilišni studij elektrotehnika'), (4, 'Diplomski sveučilišni studij računarstvo'), (5, 'Preddiplomski sveučilišni studij strojarstvo'), (6, 'Preddiplomski sveučilišni studij brodogradnja'), (7, 'Preddiplomski sveučilišni studij elektrotehnika'), (8, 'Preddiplomski sveučilišni studij računarstvo'), (9, 'Preddiplomski stručni studij strojarstvo'), (10, 'Preddiplomski stručni studij brodogradnja'), (11, 'Preddiplomski stručni studij elektrotehnika')], primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'studies',
            },
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, upload_to='')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Završni rad'), (2, 'Diplomski rad')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'SPREMLJEN'), (2, 'PREDAN MENTORU'), (3, 'PROVJEREN'), (4, 'PREDAN POVJERENSTVU'), (5, 'PRIHVAĆEN'), (6, 'ODBIJEN'), (7, 'U DORADI'), (8, 'OBRANJEN')], default=1)),
                ('remark', models.TextField(blank=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('verification_of_authenticity', models.FileField(blank=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Student')),
                ('deputy_of_thesis_comitee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zamjenik_povjerenstva', to='administration.Employee')),
                ('komentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='komentor', to='administration.Employee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='administration.Employee')),
                ('president_of_thesis_comitee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predsjednik_povjerenstva', to='administration.Employee')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Study')),
                ('writer_of_thesis_comitee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='djelovođa_povjerenstva', to='administration.Employee')),
            ],
            options={
                'verbose_name_plural': 'theses',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'SENT'), (2, 'READ')], default=1)),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberOfThesisComitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('defense_grade', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Employee')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Thesis')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(to='administration.Role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
