# Generated by Django 3.0.8 on 2020-08-23 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'DJELATNICI',
                'db_table': 'DJELATNIK',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'predsjednik povjerenstva za diplomske ispite - strojarstvo'), (2, 'zamjenik povjerenstva za diplomske ispite - strojarstvo'), (3, 'djelovođa povjerenstva za diplomske ispite - strojarstvo'), (4, 'predsjednik povjerenstva za diplomske ispite - brodogradnja'), (5, 'zamjenik povjerenstva za diplomske ispite - brodogradnja'), (6, 'djelovođa povjerenstva za diplomske ispite - brodogradnja'), (7, 'predsjednik povjerenstva za diplomske ispite - elektrotehnika'), (8, 'zamjenik povjerenstva za diplomske ispite - elektrotehnika'), (9, 'djelovođa povjerenstva za diplomske ispite - elektrotehnika'), (10, 'predsjednik povjerenstva za diplomske ispite - računarstvo'), (11, 'zamjenik povjerenstva za diplomske ispite - računarstvo'), (12, 'djelovođa povjerenstva za diplomske ispite - računarstvo'), (13, 'predsjednik povjerenstva za završne ispite - strojarstvo sveučilišni'), (14, 'zamjenik povjerenstva za završne ispite - strojarstvo sveučilišni'), (15, 'djelovođa povjerenstva za završne ispite - strojarstvo sveučilišni'), (16, 'predsjednik povjerenstva za završne ispite - brodogradnja sveučilišni'), (17, 'zamjenik povjerenstva za završne ispite - brodogradnja sveučilišni'), (18, 'djelovođa povjerenstva za završne ispite - brodogradnja sveučilišni'), (19, 'predsjednik povjerenstva za završne ispite - elektrotehnika sveučilišni'), (20, 'zamjenik povjerenstva za završne ispite - elektrotehnika sveučilišni'), (21, 'djelovođa povjerenstva za završne ispite - elektrotehnika sveučilišni'), (22, 'predsjednik povjerenstva za završne ispite - računarstvo sveučilišni'), (23, 'zamjenik povjerenstva za završne ispite - računarstvo sveučilišni'), (24, 'djelovođa povjerenstva za završne ispite - računarstvo sveučilišni'), (25, 'predsjednik povjerenstva za završne ispite - strojarstvo stručni'), (26, 'zamjenik povjerenstva za završne ispite - strojarstvo stručni'), (27, 'djelovođa povjerenstva za završne ispite - strojarstvo stručni'), (28, 'predsjednik povjerenstva za završne ispite - brodogradnja stručni'), (29, 'zamjenik povjerenstva za završne ispite - brodogradnja stručni'), (30, 'djelovođa povjerenstva za završne ispite - brodogradnja stručni'), (31, 'predsjednik povjerenstva za završne ispite - elektrotehnika stručni'), (32, 'zamjenik povjerenstva za završne ispite - elektrotehnika stručni'), (33, 'djelovođa povjerenstva za završne ispite - elektrotehnika stručni'), (34, 'mentor'), (35, 'komentor')], primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'ULOGE',
                'db_table': 'ULOGA',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_study', models.CharField(max_length=50, verbose_name='podrucjeZnanosti')),
                ('category', models.CharField(max_length=50, verbose_name='vrstaStudenta')),
                ('jmbag', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Korisnik')),
            ],
            options={
                'verbose_name_plural': 'STUDENTI',
                'db_table': 'STUDENT',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Diplomski sveučilišni studij strojarstvo'), (2, 'Diplomski sveučilišni studij brodogradnja'), (3, 'Diplomski sveučilišni studij elektrotehnika'), (4, 'Diplomski sveučilišni studij računarstvo'), (5, 'Preddiplomski sveučilišni studij strojarstvo'), (6, 'Preddiplomski sveučilišni studij brodogradnja'), (7, 'Preddiplomski sveučilišni studij elektrotehnika'), (8, 'Preddiplomski sveučilišni studij računarstvo'), (9, 'Preddiplomski stručni studij strojarstvo'), (10, 'Preddiplomski stručni studij brodogradnja'), (11, 'Preddiplomski stručni studij elektrotehnika')], primary_key=True, serialize=False)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'ZAVRŠNI RAD'), (2, 'DIPLOMSKI RAD')], default=1, verbose_name='tipRadaNaStudiju')),
            ],
            options={
                'verbose_name_plural': 'STUDIJI',
                'db_table': 'STUDIJ',
            },
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='naslov')),
                ('title_english', models.CharField(blank=True, max_length=100, null=True, verbose_name='naslovEngleski')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='sadrzaj')),
                ('summary_english', models.TextField(blank=True, null=True, verbose_name='sadrzajEngleski')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='dokumentRada')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'SPREMLJEN'), (2, 'PREDAN MENTORU'), (3, 'PROVJEREN'), (4, 'PREDAN POVJERENSTVU'), (5, 'ODBIJEN'), (6, 'U DORADI'), (7, 'PRIHVAĆEN'), (8, 'OBRANJEN'), (9, 'NIJE POLOŽEN')], default=1)),
                ('remark', models.TextField(blank=True, verbose_name='napomena')),
                ('date', models.DateField(verbose_name='datumPredaje')),
                ('verification_of_authenticity', models.FileField(blank=True, upload_to='', verbose_name='dokumentProvjereIzvornosti')),
                ('final_grade', models.IntegerField(blank=True, null=True, verbose_name='konacnaOcjena')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Student', verbose_name='Student')),
                ('komentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='komentor', to='administration.Employee', verbose_name='Komentor')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='administration.Employee', verbose_name='Mentor')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Study', verbose_name='Studij')),
            ],
            options={
                'verbose_name_plural': 'ZAVRSNI/DIPLOMSKI RADOVI',
                'db_table': 'ZAVRSNI/DIPLOMSKI RAD',
            },
        ),
        migrations.CreateModel(
            name='StudyComitee',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Povjerenstvo za diplomske ispite diplomskog sveučilišnog studija strojarstva'), (2, 'Povjerenstvo za diplomske ispite diplomskog sveučilišnog studija brodogradnje'), (3, 'Povjerenstvo za diplomske ispite diplomskog sveučilišnog studija elektrotehnike'), (4, 'Povjerenstvo za diplomske ispite diplomskog sveučilišnog studija računarstva'), (5, 'Povjerenstvo za završne ispite preddiplomskog sveučilišnog studija strojarstva'), (6, 'Povjerenstvo za završne ispite preddiplomskog sveučilišnog studija brodogradnje'), (7, 'Povjerenstvo za završne ispite preddiplomskog sveučilišnog studija elektrotehnike'), (8, 'Povjerenstvo za završne ispite preddiplomskog sveučilišnog studija računarstva'), (9, 'Povjerenstvo za završne ispite preddiplomskog stručnog studija strojarstva'), (10, 'Povjerenstvo za završne ispite preddiplomskog stručnog studija brodogradnje'), (11, 'Povjerenstvo za završne ispite preddiplomskog stručnog studija elektrotehnike')], primary_key=True, serialize=False)),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deputy', to='administration.Employee', verbose_name='Zamjenik')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president', to='administration.Employee', verbose_name='Predsjednik')),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.Study', verbose_name='Studij')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='administration.Employee', verbose_name='Djelovoda')),
            ],
            options={
                'verbose_name_plural': 'POVJERENSTVA_ZA_ZAVRSNE/DIPLOMSKE_ISPITE',
                'db_table': 'POVJERENSTVO_ZA_ZAVRSNE/DIPLOMSKE_ISPITE',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Predmet')),
                ('content', models.TextField(verbose_name='sadrzaj')),
                ('status', models.PositiveSmallIntegerField(choices=[(2, 'READ'), (1, 'SENT')], default=1)),
                ('date', models.DateTimeField(verbose_name='datum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Korisnik')),
            ],
            options={
                'verbose_name_plural': 'OBAVIJESTI',
                'db_table': 'OBAVIJEST',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(to='administration.Role', verbose_name='Uloge'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Korisnik'),
        ),
        migrations.CreateModel(
            name='MemberOfThesisComitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='ocjenaRad')),
                ('defense_grade', models.IntegerField(blank=True, null=True, verbose_name='ocjenaObrane')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Employee', verbose_name='Djelatnik')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Thesis', verbose_name='Rad')),
            ],
            options={
                'verbose_name_plural': 'CLANOVI_POVJERENSTVA_ZA_OBRANU',
                'db_table': 'CLAN_POVJERENSTVA_ZA_OBRANU',
                'unique_together': {('thesis', 'employee')},
            },
        ),
    ]
