# Generated by Django 3.0.8 on 2020-08-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='summary',
            field=models.TextField(default='sažetak'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='summary_english',
            field=models.TextField(default='sažetak na engleskom'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='title_english',
            field=models.CharField(default='naslov na engleskom', max_length=100),
        ),
    ]
