# Generated by Django 3.0.8 on 2020-08-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20200810_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='summary',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='summary_english',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='title_english',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
