# Generated by Django 3.0.8 on 2020-08-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20200810_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='defense_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thesis',
            name='final_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'READ'), (1, 'SENT')], default=1),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SPREMLJEN'), (2, 'PREDAN MENTORU'), (3, 'PROVJEREN'), (4, 'PREDAN POVJERENSTVU'), (5, 'PRIHVAĆEN'), (6, 'ODBIJEN'), (7, 'U DORADI'), (8, 'OBRANJEN'), (9, 'NIJE POLOŽEN')], default=1),
        ),
    ]
