# Generated by Django 3.0.8 on 2020-08-12 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20200811_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.datetime),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SENT'), (2, 'READ')], default=1),
        ),
    ]
