# Generated by Django 3.0.8 on 2020-08-12 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20200812_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 12, 4, 21, 24, 467588)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'READ'), (1, 'SENT')], default=1),
        ),
    ]
