# Generated by Django 3.0.8 on 2020-08-12 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_auto_20200812_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 12, 4, 27, 31, 292478)),
        ),
    ]
