# Generated by Django 3.0.8 on 2020-08-12 04:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20200812_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 12, 4, 31, 48, 313688, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SENT'), (2, 'READ')], default=1),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 12, 4, 31, 48, 312637, tzinfo=utc)),
        ),
    ]
