# Generated by Django 3.0.8 on 2020-08-12 21:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_auto_20200812_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='defense_grade',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='grade',
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 21, 59, 40, 900701, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 12, 21, 59, 40, 899646, tzinfo=utc)),
        ),
    ]
