# Generated by Django 3.0.8 on 2020-08-13 18:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_auto_20200812_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 18, 58, 46, 535380, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'READ'), (1, 'SENT')], default=1),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'predsjednik povjerenstva za diplomske ispite - strojarstvo'), (2, 'zamjenik povjerenstva za diplomske ispite - strojarstvo'), (3, 'djelovođa povjerenstva za diplomske ispite - strojarstvo'), (4, 'predsjednik povjerenstva za diplomske ispite - brodogradnja'), (5, 'zamjenik povjerenstva za diplomske ispite - brodogradnja'), (6, 'djelovođa povjerenstva za diplomske ispite - brodogradnja'), (7, 'predsjednik povjerenstva za diplomske ispite - elektrotehnika'), (8, 'zamjenik povjerenstva za diplomske ispite - elektrotehnika'), (9, 'djelovođa povjerenstva za diplomske ispite - elektrotehnika'), (10, 'predsjednik povjerenstva za diplomske ispite - računarstvo'), (11, 'zamjenik povjerenstva za diplomske ispite - računarstvo'), (12, 'djelovođa povjerenstva za diplomske ispite - računarstvo'), (13, 'predsjednik povjerenstva za završne ispite - strojarstvo sveučilišni'), (14, 'zamjenik povjerenstva za završne ispite - strojarstvo sveučilišni'), (15, 'djelovođa povjerenstva za završne ispite - strojarstvo sveučilišni'), (16, 'predsjednik povjerenstva za završne ispite - brodogradnja sveučilišni'), (17, 'zamjenik povjerenstva za završne ispite - brodogradnja sveučilišni'), (18, 'djelovođa povjerenstva za završne ispite - brodogradnja sveučilišni'), (19, 'predsjednik povjerenstva za završne ispite - elektrotehnika sveučilišni'), (20, 'zamjenik povjerenstva za završne ispite - elektrotehnika sveučilišni'), (21, 'djelovođa povjerenstva za završne ispite - elektrotehnika sveučilišni'), (22, 'predsjednik povjerenstva za završne ispite - računarstvo sveučilišni'), (23, 'zamjenik povjerenstva za završne ispite - računarstvo sveučilišni'), (24, 'djelovođa povjerenstva za završne ispite - računarstvo sveučilišni'), (25, 'predsjednik povjerenstva za završne ispite - strojarstvo stručni'), (26, 'zamjenik povjerenstva za završne ispite - strojarstvo stručni'), (27, 'djelovođa povjerenstva za završne ispite - strojarstvo stručni'), (28, 'predsjednik povjerenstva za završne ispite - brodogradnja stručni'), (29, 'zamjenik povjerenstva za završne ispite - brodogradnja stručni'), (30, 'djelovođa povjerenstva za završne ispite - brodogradnja stručni'), (31, 'predsjednik povjerenstva za završne ispite - elektrotehnika stručni'), (32, 'zamjenik povjerenstva za završne ispite - elektrotehnika stručni'), (33, 'djelovođa povjerenstva za završne ispite - elektrotehnika stručni'), (34, 'mentor'), (35, 'komentor')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 13, 18, 58, 46, 534257, tzinfo=utc)),
        ),
    ]
