# Generated by Django 3.1 on 2020-08-14 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_auto_20200813_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 9, 5, 15, 552817, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SENT'), (2, 'READ')], default=1),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 14, 9, 5, 15, 551714, tzinfo=utc)),
        ),
    ]
