# Generated by Django 3.0.8 on 2020-08-15 19:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_auto_20200814_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 15, 19, 58, 33, 787541, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 15, 19, 58, 33, 786456, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='StudyComitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamjenik', to='administration.Employee')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predsjednik', to='administration.Employee')),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.Study')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='djelovođa', to='administration.Employee')),
            ],
        ),
    ]
