# Generated by Django 3.0.8 on 2020-08-15 21:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_auto_20200815_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='deputy_of_thesis_comitee',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='president_of_thesis_comitee',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='writer_of_thesis_comitee',
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 15, 21, 28, 16, 788178, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studycomitee',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='djelovoda', to='administration.Employee'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 15, 21, 28, 16, 787195, tzinfo=utc)),
        ),
    ]
